export const TITLE = 'Typing speed test'
export const GAME_MODE_FAST = 'fast-game'
export const LINKEDIN_LINK = 'https://www.linkedin.com/in/wojciech-guze/'
export const GITHUB_LINK = 'https://github.com/wojciechguze2'
export const MAIL_LINK = 'mailto:wojciechguze2@gmail.com'
export const PHONE_LINK = 'tel:+48518118593'
export const PHONE = '+48518118593'
export const MAIL = 'wojciechguze2@gmail.com'
export const RECAPTCHA_KEY = '6LezPcInAAAAABoGLD2EJ6q84D2FWrR2FwTZNVvU'
export const EMAIL_NOT_VALID_MESSAGE = 'Niepoprawny adres e-mail.'
export const LOGIN_ERROR_MESSAGE = 'Nie znaleziono użytkownika.'
export const USER_IS_NOT_ACTIVE_MESSAGE = 'Użytkownik jest nieaktywny. <a href="/kontakt">Kontakt</a>'
export const REGISTER_ERROR_MESSAGE = 'Wystąpiły błędy przy tworzeniu użytkownika.'
export const USER_ALREADY_EXISTS_MESSAGE = 'Użytkownik z podanym adresem e-mail już istnieje.'
export const REGISTER_ENABLED = true
export const PASSWORD_REMINDER_ENABLED = true
export const REGISTER_NEED_ADMIN_ACCEPT = false
export const LOGIN_SUCCESS_REDIRECT_URL = '/'
export const REGISTER_SUCCESS_REDIRECT_URL = '/'
export const DEFAULT_AUTHENTICATED_REDIRECT_URL = '/'
export const DEFAULT_NOT_AUTHENTICATED_REDIRECT_URL = '/login'
export const LOGOUT_URL = '/logout'
export const ACCOUNT_EMAIL_CHANGE_AVAILABLE = false
export const HOMEPAGE_SPECIAL_TYPING_SPEED = 75
export const HOMEPAGE_SPECIAL_TYPING_COUNTDOWN = 500